import React from 'react';
import { Provider } from 'react-redux';

import Head from 'next/head';
import App from '../components/_app';
import { store } from '../store';

export const Home = () => {
  return (
    <div>
      <Head>
        <title>Rover Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Provider store={store}>
        <App />
      </Provider>
    </div>
  );
};

export default Home;
